### ISSUE TITLE
Bug in s.number matcher with value of min or max is 0

### ISSUE THREAD

**Issue by mehdivk** [TabDigital/strummer#20]
Hi,
There is a bug in s.number matchers when `min` or `max` is `0`. An example:
```javascript
var s = require('strummer');
var ageValidator = s.number({min: 0});
var validate = s({age: ageValidator});
var catchMeIfYouCan = {age: 0};

console.log(validate(catchMeIfYouCan));
```

Issue is with `if (opts.min && opts.max && (value < opts.min || value > opts.max)) {`.
 `0`, `false` and `empty string` can't pass `if(some_var)`.

A helper needed here to just check value of `min` against being `null` or `undefined`. Something like

```javascript
//utils.js

var hasValue = function(val) {
  return (typeof val !== 'undefined') && (val !== null);
}

module.exports = {
   hasValue: hasValue
}

```

This bug is available in some other matchers as well.

**Comment by mehdivk** [comment]
@nguyenchr @rprieto If you guys are happy with the hasValue helper solution I can apply it else happy to hear about ur solution.

**Comment by nguyenchr** [comment]
good pickup, I guess we havn't run into this before as you don't generally set `min` or `max` values to be `0`

`hasValue` looks like a good solution

**Comment by mehdivk** [comment]
Cool, I will comeback with a PR

**Comment by srushti** [comment]
Presumably this can be closed, now that the PR has been merged.

**Comment by mehdivk** [comment]
@srushti :+1:
