### ISSUE TITLE
isoDate should only have date

### ISSUE THREAD

**Issue by srushti** [TabDigital/strummer#23]
The current `isoDate` should really only look for a date, and we could introduce a new matcher (`isoDateTime` maybe) to match date and time. Or at the very least `isoDate` should take a `time: false` or something similar.

What do you think?

**Comment by rprieto** [comment]
:+1: for clarity.
This was supposed to be "typical" ISO 8601, but the RFC has many valid formats, including (but not limited to)

- `2015-03-24`
- `2015-03-24T06:57:23+00:00`
- `2015-03-24T06:57:23Z`

Not sure what we should aim to cover here. I like your idea of `time`. What about:

- `time: true/false`? (ensures there's either a `T` component, or nothing)
- `gmt: true/false`? (ensures there's either a `Z`, or an offset/nothing)

For all cases we should probably accept the widest possible ISO format. After all it's up to another library to parse it, so strummer should not be restrictive.

**Comment by srushti** [comment]
`gmt` or `timezone`, maybe. I'll write something up.
