### ISSUE TITLE
Identify data type from route parameter validation 

### ISSUE THREAD

**Issue by mkhanal** [TabDigital/strummer#36]
I'm trying to build a restful interface and use strummer to validate my path parameters in the route.
If I need to validate a number, I would prefer to use 'number' or 'integer' type in strummer.

However, 
```javascript
validate: {
    params: s({
      id: 'number'
    })
  }
```
would fail for the route
```javascript
http://domain:port/resource/5 
```
where 5 is mapped to id.

This is because strummer sees 5 as a string. The same goes for other types like boolean. 
To overcome this, I have to create either a regex, which does not give a good message on failure, or I have to create a custom matcher.

It would be nice to allow parsing of this type. If this feature might cause problems for the generic use, a flag such as 'inferType' that I can set to true as:
```javascript
id: new s.number({"inferType": true})
```

**Comment by rprieto** [comment]
That's a common use case :+1: strummer has `s.number({parse: true})`, `s.integer({parse: true}`, `s.boolean({parse: true})` that should solve your problem.

**Comment by mkhanal** [comment]
Oh..thanks....that's exactly what I needed
...We can add it to docs probably .

**Comment by rprieto** [comment]
[README/matchers](MATCHERS.md) :)
